# Generated by Django 6.0.3 on 2026-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
