# Generated by Django 6.0.3 on 2026-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmodel',
            name='conversation_id',
            field=models.CharField(max_length=255),
        ),
    ]
