# Generated by Django 6.0.3 on 2026-03-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversationmodel_conversation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='conversationmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
    ]
