# Generated by Django 6.0.3 on 2026-04-27 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_options_alter_conversationmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=2048)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chat.chat')),
            ],
            options={
                'db_table': 'chat_media',
            },
        ),
    ]
