# Generated by Django 6.0.3 on 2026-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
