# Generated by Django 6.0.3 on 2026-05-13 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversationmodel_is_deleted'),
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='cohort.cohort'),
        ),
    ]
