# Generated by Django 6.0.3 on 2026-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
