# Generated by Django 6.0.3 on 2026-06-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversationmodel_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
