# Generated by Django 6.0.3 on 2026-06-25 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='minimum age')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='maximum age')),
                ('guardrails', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Guardrail Rule',
                'verbose_name_plural': 'Guardrail Rules',
                'db_table': 'guardrail_rule',
                'ordering': ['min_age', 'max_age'],
            },
        ),
    ]
