/**
 * Mock data for dashboard demonstration.
 * Replace with real API calls in production.
 */

export const recentParticipants = [
  {
    id: "P001",
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    study: "Cognitive Behavior Study",
    status: "active",
    joinedAt: "2025-02-28",
    progress: 75,
    initials: "SJ",
  },
  {
    id: "P002",
    name: "Michael Chen",
    email: "m.chen@example.com",
    study: "Sleep Pattern Analysis",
    status: "pending",
    joinedAt: "2025-03-01",
    progress: 20,
    initials: "MC",
  },
  {
    id: "P003",
    name: "Amara Okafor",
    email: "a.okafor@example.com",
    study: "Dietary Habits Research",
    status: "active",
    joinedAt: "2025-03-03",
    progress: 50,
    initials: "AO",
  },
  {
    id: "P004",
    name: "Luca Rossi",
    email: "l.rossi@example.com",
    study: "Cognitive Behavior Study",
    status: "completed",
    joinedAt: "2025-02-20",
    progress: 100,
    initials: "LR",
  },
  {
    id: "P005",
    name: "Priya Sharma",
    email: "p.sharma@example.com",
    study: "Mental Health Tracking",
    status: "inactive",
    joinedAt: "2025-02-15",
    progress: 30,
    initials: "PS",
  },
];

export const recentResearchers = [
  {
    id: "R001",
    name: "Dr. James Wheeler",
    email: "j.wheeler@university.edu",
    department: "Neuroscience",
    activeStudies: 3,
    totalParticipants: 142,
    status: "active",
    joinedAt: "2023-09-01",
    initials: "JW",
    specialty: "Cognitive Sciences",
  },
  {
    id: "R002",
    name: "Dr. Mei Lin",
    email: "mei.lin@university.edu",
    department: "Psychology",
    activeStudies: 2,
    totalParticipants: 98,
    status: "active",
    joinedAt: "2024-01-15",
    initials: "ML",
    specialty: "Behavioral Psychology",
  },
  {
    id: "R003",
    name: "Prof. Hassan Al-Rashid",
    email: "h.alrashid@research.org",
    department: "Epidemiology",
    activeStudies: 1,
    totalParticipants: 215,
    status: "active",
    joinedAt: "2022-06-10",
    initials: "HR",
    specialty: "Public Health",
  },
  {
    id: "R004",
    name: "Dr. Elena Vasquez",
    email: "e.vasquez@institute.edu",
    department: "Nutrition Science",
    activeStudies: 2,
    totalParticipants: 67,
    status: "pending",
    joinedAt: "2025-01-20",
    initials: "EV",
    specialty: "Dietary Research",
  },
];

export const statsData = [
  {
    title: "Total Participants",
    value: "1,284",
    change: "+12%",
    trend: "up",
    description: "vs last month",
  },
  {
    title: "Active Researchers",
    value: "38",
    change: "+3",
    trend: "up",
    description: "vs last month",
  },
  {
    title: "Ongoing Studies",
    value: "14",
    change: "-1",
    trend: "down",
    description: "vs last month",
  },
  {
    title: "Completion Rate",
    value: "68%",
    change: "+5%",
    trend: "up",
    description: "vs last month",
  },
];
