# Generated by Django 6.0.3 on 2026-06-29 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email_host', models.CharField(max_length=255, verbose_name='email host')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='email port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='use TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='use SSL')),
                ('email_host_user', models.CharField(max_length=255, verbose_name='email host user')),
                ('email_host_password', models.TextField(verbose_name='email host password')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='default from email')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'db_table': 'email_configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
