# Generated by Django 6.0.3 on 2026-06-29 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('web_search', models.BooleanField(default=False, verbose_name='web search')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configuration',
                'db_table': 'global_configuration',
            },
        ),
    ]
