# Generated by Django 6.0.3 on 2026-05-25 10:34

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0003_alter_cohort_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='cohort_name_case_insensitive_unique'),
        ),
    ]
