# Generated by Django 6.0.3 on 2026-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='has_accepted',
            field=models.BooleanField(default=False, verbose_name='has accepted'),
        ),
    ]
