# Generated by Django 6.0.3 on 2026-03-19 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_invitation_has_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'guardian',
            },
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='participant_invitation',
        ),
        migrations.AlterModelTable(
            name='participantprofile',
            table='participant_profile',
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='guardian',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to='participant.guardian'),
        ),
    ]
