# Generated by Django 6.0.3 on 2026-03-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_guardian_alter_invitation_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='parent_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
