# Generated by Django 6.0.3 on 2026-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_participantprofile_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, null=True, verbose_name='gender'),
        ),
    ]
