# Generated by Django 6.0.3 on 2026-05-13 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
        ('participant', '0006_alter_participantprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='cohort.cohort'),
        ),
    ]
